library(shiny)
library(shinyWidgets)
library(shinydashboard)
library(here)
library(log4r)
library(gt)
library(officer)
library(yaml)
library(scales)
library(glue)
library(tidyr)
library(huxtable)
library(IncidencePrevalence)
library(DT)
library(dplyr)

sourceFiles <- list.files(path = "modules", full.names = T)
sapply(sourceFiles, source)
