IncidencePrevalence:
  attrition:
    names:
    - cohort_definition_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
    - group_name
    - cdm_name
TreatmentPatterns:
  treatmentPathways:
    names:
    - path
    - freq
    - sex
    - age
    - indexYear
cohortAttrition:
  cohortAttrition:
    names:
    - cohort_definition_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects



