IncidencePrevalence:
  attrition:
    names:
    - cohort_definition_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects
    - group_name
    - cdm_name
TreatmentPatterns:
  treatmentPathways:
    names:
    - pathway
    - freq
    - age
    - sex
    - index_year
    - analysis_id
    - target_cohort_id
cohortAttrition:
  cohortAttrition:
    names:
    - cohort_definition_id
    - number_records
    - number_subjects
    - reason_id
    - reason
    - excluded_records
    - excluded_subjects



